package config

import (
	"fmt"
	"os"
)

// DefaultConfig returns a Config with sensible default values
func DefaultConfig() *Config {
	return &Config{
		ScanDir: "scans",
		DBPath:  "reconpipe.db",
		Tools: ToolsConfig{
			Subfinder: ToolConfig{
				Path:    "subfinder",
				Args:    []string{"-silent"},
				Timeout: "5m",
			},
			Tlsx: ToolConfig{
				Path:    "tlsx",
				Args:    []string{"-silent"},
				Timeout: "5m",
			},
			Dig: ToolConfig{
				Path:    "dig",
				Args:    []string{"+short"},
				Timeout: "5m",
			},
			Masscan: ToolConfig{
				Path:    "masscan",
				Args:    []string{"-p1-65535", "--rate=1000"},
				Timeout: "5m",
			},
			Nmap: ToolConfig{
				Path:    "nmap",
				Args:    []string{"-sV", "-Pn"},
				Timeout: "5m",
			},
			Httpx: ToolConfig{
				Path:    "httpx",
				Args:    []string{"-silent"},
				Timeout: "5m",
			},
			Gowitness: ToolConfig{
				Path:    "gowitness",
				Args:    []string{"single"},
				Timeout: "5m",
			},
			Cdncheck: ToolConfig{
				Path:    "cdncheck",
				Args:    []string{"-silent"},
				Timeout: "5m",
			},
			Nuclei: ToolConfig{
				Path:    "nuclei",
				Args:    []string{"-silent"},
				Timeout: "5m",
			},
		},
		RateLimits: RateLimitConfig{
			SubfinderThreads: 10,
			MasscanRate:      1000,
			NmapMaxParallel:  5,
			HttpxThreads:     25,
			NucleiThreads:    10,
			NucleiRateLimit:  150,
		},
		Stages: StagesConfig{
			Enable: []string{},
			Skip:   []string{},
		},
	}
}

// WriteDefault writes a default configuration to the specified path
func WriteDefault(path string) error {
	// Create a YAML node with proper field names (matching mapstructure tags)
	yamlContent := `# ReconPipe Configuration
# Generated by 'reconpipe init'

# Directory where scan results will be stored
scan_dir: scans

# Path to bbolt database for scan metadata
db_path: reconpipe.db

# External tool configurations
tools:
  subfinder:
    path: subfinder
    args:
      - -silent
    timeout: 5m
  tlsx:
    path: tlsx
    args:
      - -silent
    timeout: 5m
  dig:
    path: dig
    args:
      - +short
    timeout: 5m
  masscan:
    path: masscan
    args:
      - -p1-65535
      - --rate=1000
    timeout: 5m
  nmap:
    path: nmap
    args:
      - -sV
      - -Pn
    timeout: 5m
  httpx:
    path: httpx
    args:
      - -silent
    timeout: 5m
  gowitness:
    path: gowitness
    args:
      - single
    timeout: 5m
  cdncheck:
    path: cdncheck
    args:
      - -silent
    timeout: 5m
  nuclei:
    path: nuclei
    args:
      - -silent
    timeout: 5m

# Rate limiting settings for tools
rate_limits:
  subfinder_threads: 10
  masscan_rate: 1000
  nmap_max_parallel: 5
  httpx_threads: 25
  nuclei_threads: 10
  nuclei_rate_limit: 150

# Pipeline stage control
stages:
  enable: []  # Enable only specific stages (empty = all enabled)
  skip: []    # Skip specific stages
`

	if err := os.WriteFile(path, []byte(yamlContent), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}
